import { Verse, WisdomQuote, Devotional } from './types';

export const APP_ID = 'husbands-devotional';

export const VERSE_LIBRARY: Verse[] = [
  { reference: "1 Corinthians 13:4-8", text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", topic: "Marriage" },
  { reference: "Ephesians 5:25", text: "Husbands, love your wives, just as Christ loved the church and gave himself up for her.", topic: "Marriage" },
  { reference: "Ephesians 5:33", text: "However, each one of you also must love his wife as he loves himself, and the wife must respect her husband.", topic: "Marriage" },
  { reference: "Pro 16:32", text: "Better to be patient than powerful; better to have self-control than to conquer a city.", topic: "Anger" },
  { reference: "Proverbs 11:12", text: "The one who denounces his neighbor lacks sense, but a discerning person keeps silent.", topic: "Speech" },
  { reference: "Proverbs 11:3", text: "The integrity of the upright guides them, but the crookedness of the treacherous destroys them.", topic: "Integrity" },
  { reference: "Proverbs 12:1", text: "The one who loves discipline loves knowledge, but the one who hates reproof is stupid.", topic: "Wisdom" },
  { reference: "Proverbs 12:4", text: "A noble wife is the crown of her husband, but the wife who acts shamefully is like rottenness in his bones.", topic: "Marriage" },
  { reference: "Proverbs 13:16", text: "Every shrewd person acts with knowledge, but a fool displays his folly.", topic: "Wisdom" },
  { reference: "Proverbs 13:20", text: "The one who associates with the wise grows wise, but a companion of fools suffers harm.", topic: "Friendship" },
  { reference: "Proverbs 14:1", text: "Every wise woman has built her household, but a foolish woman tears it down with her own hands.", topic: "Marriage" },
  { reference: "Proverbs 14:22", text: "Do not those who devise evil go astray? But those who plan good exhibit faithful covenant love.", topic: "Integrity" },
  { reference: "Proverbs 18:13", text: "The one who gives an answer before he listens – that is his folly and his shame.", topic: "Speech" },
  { reference: "Proverbs 18:19", text: "A relative offended is harder to reach than a strong city, and disputes are like the barred gates of a fortified citadel.", topic: "Wisdom" },
  { reference: "Proverbs 18:2", text: "A fool takes no pleasure in understanding but only in disclosing what is on his mind.", topic: "Wisdom" },
  { reference: "Proverbs 18:21", text: "Death and life are in the power of the tongue, and those who love its use will eat its fruit.", topic: "Speech" },
  { reference: "Proverbs 20:6", text: "Many people profess their loyalty, but a faithful person – who can find?", topic: "Integrity" },
  { reference: "Proverbs 21:5", text: "The plans of the diligent lead only to plenty, but everyone who is hasty comes only to poverty.", topic: "Money" },
  { reference: "Proverbs 6:26", text: "for on account of a prostitute one is brought down to a loaf of bread, but the wife of another man preys on your precious life.", topic: "Marriage" },
  { reference: "Proverbs 9:6", text: "Abandon your foolish ways so that you may live, and proceed in the way of understanding.”", topic: "Wisdom" },
  { reference: "Proverbs 10:17", text: "He is in the way of life that keepeth instruction: but he that refuseth reproof erreth.", topic: "Wisdom" },
  { reference: "Proverbs 12:14", text: "A man shall be satisfied with good by the fruit of his mouth: and the recompence of a man's hands shall be rendered unto him.", topic: "Speech" },
  { reference: "Proverbs 19:19", text: "A man of great wrath shall suffer punishment: for if thou deliver him, yet thou must do it again.", topic: "Anger" },
  { reference: "Proverbs 19:20", text: "Hear counsel, and receive instruction, that thou mayest be wise in thy latter end.", topic: "Wisdom" },
  { reference: "Proverbs 20:3", text: "It is an honour for a man to cease from strife: but every fool will be meddling.", topic: "Anger" },
  { reference: "Proverbs 21:23", text: "Whoso keepeth his mouth and his tongue keepeth his soul from troubles.", topic: "Speech" },
  { reference: "Proverbs 28:9", text: "He that turneth away his ear from hearing the law, even his prayer shall be abomination.", topic: "Wisdom" },
  { reference: "Proverbs 29:11", text: "A fool uttereth all his mind: but a wise man keepeth it in till afterwards.", topic: "Wisdom" },
  { reference: "Proverbs 17:1", text: "Better is a dry crust of bread where there is quietness than a house full of feasting with strife.", topic: "Anger" },
  { reference: "Proverbs 17:13", text: "As for the one who repays evil for good, evil will not leave his house.", topic: "Integrity" },
  { reference: "Proverbs 19:3", text: "A person’s folly subverts his way, and his heart rages against the LORD.", topic: "Heart" },
  { reference: "Proverbs 2:7", text: "He stores up effective counsel for the upright, and is like a shield for those who live with integrity,", topic: "Integrity" },
  { reference: "Proverbs 21:19", text: "It is better to live in the wilderness than with a quarrelsome and easily-provoked woman.", topic: "Marriage" },
  { reference: "Proverbs 24:29", text: "Do not say, “I will do to him just as he has done to me; I will pay him back according to what he has done.”", topic: "Integrity" },
  { reference: "Proverbs 24:3", text: "By wisdom a house is built, and through understanding it is established;", topic: "Wisdom" },
  { reference: "Proverbs 24:4", text: "by knowledge its rooms are filled with all kinds of precious and pleasing treasures.", topic: "Wisdom" },
  { reference: "Proverbs 25:15", text: "Through patience a ruler can be persuaded, and a soft tongue can break a bone.", topic: "Speech" },
  { reference: "Proverbs 25:19", text: "Like a bad tooth or a foot out of joint, so is confidence in an unfaithful person at the time of trouble.", topic: "Wisdom" },
  { reference: "Proverbs 25:24", text: "It is better to live on a corner of the housetop than in a house in company with a quarrelsome wife.", topic: "Marriage" },
  { reference: "Proverbs 25:28", text: "Like a city that is broken down and without a wall, so is a person who cannot control his temper.", topic: "Anger" },
  { reference: "Proverbs 26:18", text: "Like a madman who shoots firebrands and deadly arrows,", topic: "Wisdom" },
  { reference: "Proverbs 26:19", text: "so is a person who has deceived his neighbor, and said, “Was I not only joking?”", topic: "Friendship" },
  { reference: "Proverbs 27:15", text: "A continual dripping on a rainy day– a contentious wife makes herself like that.", topic: "Marriage" },
  { reference: "Proverbs 27:19", text: "As in water the face is reflected as a face, so a person’s heart reflects the person.", topic: "Heart" },
  { reference: "Proverbs 27:23", text: "Pay careful attention to the condition of your flocks, set your mind on your herds,", topic: "Wisdom" },
  { reference: "Proverbs 28:19", text: "The one who works his land will be satisfied with food, but whoever chases daydreams will have his fill of poverty.", topic: "Money" },
  { reference: "Proverbs 29:1", text: "The one who stiffens his neck after numerous rebukes will suddenly be destroyed without remedy.", topic: "Wisdom" },
  { reference: "Proverbs 29:20", text: "You have seen someone who is hasty in his words– there is more hope for a fool than for him.", topic: "Speech" },
  { reference: "Proverbs 29:22", text: "An angry person stirs up dissension, and a wrathful person is abounding in transgression.", topic: "Anger" },
  { reference: "Proverbs 11:25", text: "The liberal soul shall be made fat: and he that watereth shall be watered also himself.", topic: "Heart" },
  { reference: "Proverbs 12:22", text: "The LORD abhors a person who lies, but those who deal truthfully are his delight.", topic: "Wisdom" },
  { reference: "Proverbs 14:27", text: "The fear of the LORD is like a life-giving fountain, to turn people from deadly snares.", topic: "Wisdom" },
  { reference: "Proverbs 15:11", text: "Death and Destruction are before the LORD – how much more the hearts of humans!", topic: "Wisdom" },
  { reference: "Proverbs 15:26", text: "The LORD abhors the plans of the wicked, but pleasant words are pure.", topic: "Speech" },
  { reference: "Proverbs 16:7", text: "When a person’s ways are pleasing to the LORD, he even reconciles his enemies to himself.", topic: "Wisdom" },
  { reference: "Proverbs 16:9", text: "A person plans his course, but the LORD directs his steps.", topic: "Wisdom" },
  { reference: "Proverbs 2:8", text: "to guard the paths of the righteous and to protect the way of his pious ones.", topic: "Integrity" },
  { reference: "Proverbs 21:1", text: "The king’s heart is in the hand of the LORD like channels of water; he turns it wherever he wants.", topic: "Heart" },
  { reference: "Proverbs 21:2", text: "All of a person’s ways seem right in his own opinion, but the LORD evaluates his thoughts.", topic: "Wisdom" },
  { reference: "Proverbs 3:33", text: "The LORD’s curse is on the household of the wicked, but he blesses the home of the righteous.", topic: "Integrity" },
  { reference: "Proverbs 5:21", text: "For the ways of a person are in front of the LORD’s eyes, and the LORD weighs all that person’s paths.", topic: "Wisdom" },
  { reference: "Proverbs 1:8", text: "Listen, my child, to the instruction from your father, and do not forsake the teaching from your mother.", topic: "Family" },
  { reference: "Proverbs 1:9", text: "For they will be like an elegant garland on your head, and like pendants around your neck.", topic: "Wisdom" },
  { reference: "Proverbs 11:16", text: "A generous woman gains honor, and ruthless men seize wealth.", topic: "Marriage" },
  { reference: "Proverbs 11:17", text: "A kind person benefits himself, but a cruel person brings himself trouble.", topic: "Wisdom" },
  { reference: "Proverbs 11:25", text: "A generous person will be enriched, and the one who provides water for others will himself be satisfied.", topic: "Money" },
  { reference: "Proverbs 12:10", text: "A righteous person cares for the life of his animal, but even the most compassionate acts of the wicked are cruel.", topic: "Integrity" },
  { reference: "Proverbs 14:30", text: "A tranquil spirit revives the body, but envy is rottenness to the bones.", topic: "Heart" },
  { reference: "Proverbs 18:22", text: "The one who has found a good wife has found what goodness is, and obtained a delightful gift from the LORD.", topic: "Marriage" },
  { reference: "Proverbs 19:14", text: "A house and wealth are inherited from parents, but a prudent wife is from the LORD.", topic: "Marriage" },
  { reference: "Proverbs 20:28", text: "Loyal love and truth preserve a king, and his throne is upheld by loyal love.", topic: "Integrity" },
  { reference: "Proverbs 21:14", text: "A gift given in secret subdues anger, and a bribe given secretly subdues strong wrath.", topic: "Anger" },
  { reference: "Proverbs 21:21", text: "The one who pursues righteousness and love finds life, bounty, and honor.", topic: "Wisdom" },
  { reference: "Proverbs 29:6", text: "In the transgression of an evil person there is a snare, but a righteous person can sing and rejoice.", topic: "Integrity" },
  { reference: "Proverbs 31:10", text: "Who can find a wife of noble character? For her value is far more than rubies.", topic: "Marriage" },
  { reference: "Proverbs 31:12", text: "She has rewarded him with good and not harm all the days of her life.", topic: "Wisdom" },
  { reference: "Proverbs 31:20", text: "She opened her hand to the poor, and extended her hands to the needy.", topic: "Money" },
  { reference: "Proverbs 31:28", text: "Her children have risen and called her blessed; her husband also has praised her:", topic: "Marriage" },
  { reference: "Proverbs 3:29", text: "Devise not evil against thy neighbour, seeing he dwelleth securely by thee.", topic: "Integrity" },
  { reference: "Proverbs 4:25", text: "Let thine eyes look right on, and let thine eyelids look straight before thee.", topic: "Wisdom" },
  { reference: "Proverbs 6:26", text: "For by means of a whorish woman a man is brought to a piece of bread: and the adulteress will hunt for the precious life.", topic: "Marriage" },
  { reference: "Proverbs 10:12", text: "Hatred stirreth up strifes: but love covereth all sins.", topic: "Wisdom" },
  { reference: "Proverbs 11:16", text: "A gracious woman retaineth honour: and strong men retain riches.", topic: "Marriage" },
  { reference: "Proverbs 11:17", text: "The merciful man doeth good to his own soul: but he that is cruel troubleth his own flesh.", topic: "Heart" },
  { reference: "Proverbs 11:18", text: "The wicked worketh a deceitful work: but to him that soweth righteousness shall be a sure reward.", topic: "Work" },
  { reference: "Proverbs 11:24", text: "There is that scattereth, and yet increaseth; and there is that withholdeth more than is meet, but it tendeth to poverty.", topic: "Money" },
  { reference: "Proverbs 11:30", text: "The fruit of the righteous is a tree of life; and he that winneth souls is wise.", topic: "Integrity" },
  { reference: "Proverbs 14:30", text: "A sound heart is the life of the flesh: but envy the rottenness of the bones.", topic: "Heart" },
  { reference: "Proverbs 14:34", text: "Righteousness exalteth a nation: but sin is a reproach to any people.", topic: "Wisdom" },
  { reference: "Proverbs 24:32", text: "Then I saw, and considered it well: I looked upon it, and received instruction.", topic: "Wisdom" },
  { reference: "Proverbs 25:21", text: "If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink:", topic: "Money" },
  { reference: "Proverbs 4:24", text: "Put away from thee a froward mouth, and perverse lips put far from thee.", topic: "Speech" },
  { reference: "Proverbs 4:26", text: "Ponder the path of thy feet, and let all thy ways be established.", topic: "Wisdom" },
  { reference: "Proverbs 4:27", text: "Turn not to the right hand nor to the left: remove thy foot from evil.", topic: "Integrity" },
  { reference: "Proverbs 10:17", text: "The one who heeds instruction is on the way to life, but the one who rejects rebuke goes astray.", topic: "Wisdom" },
  { reference: "Proverbs 12:25", text: "Anxiety in a person’s heart weighs him down, but an encouraging word brings him joy.", topic: "Speech" },
  { reference: "Proverbs 15:1", text: "A gentle response turns away anger, but a harsh word stirs up wrath.", topic: "Speech" },
  { reference: "Proverbs 15:15", text: "All the days of the afflicted are bad, but one with a cheerful heart has a continual feast.", topic: "Heart" },
  { reference: "Proverbs 15:23", text: "A person has joy in giving an appropriate answer, and a word at the right time – how good it is!", topic: "Speech" },
  { reference: "Proverbs 15:31", text: "The person who hears the reproof that leads to life is at home among the wise.", topic: "Wisdom" },
  { reference: "Proverbs 15:33", text: "The fear of the LORD provides wise instruction, and before honor comes humility.", topic: "Pride" },
  { reference: "Proverbs 16:24", text: "Pleasant words are like a honeycomb, sweet to the soul and healing to the bones.", topic: "Speech" },
  { reference: "Proverbs 17:22", text: "A cheerful heart brings good healing, but a crushed spirit dries up the bones.", topic: "Heart" },
  { reference: "Proverbs 17:27", text: "The truly wise person restrains his words, and the one who stays calm is discerning.", topic: "Speech" },
  { reference: "Proverbs 20:11", text: "Even a young man is known by his actions, whether his activity is pure and whether it is right.", topic: "Wisdom" },
  { reference: "Proverbs 20:5", text: "Counsel in a person’s heart is like deep water, but an understanding person draws it out.", topic: "Heart" },
  { reference: "Proverbs 23:12", text: "Apply your heart to instruction and your ears to the words of knowledge.", topic: "Speech" },
  { reference: "Proverbs 24:27", text: "Establish your work outside and get your fields ready; afterward build your house.", topic: "Work" },
  { reference: "Proverbs 28:27", text: "The one who gives to the poor will not lack, but whoever shuts his eyes to them will receive many curses.", topic: "Money" },
  { reference: "Proverbs 3:29", text: "Do not plot evil against your neighbor when he dwells by you unsuspectingly.", topic: "Friendship" },
  { reference: "Proverbs 3:30", text: "Do not accuse anyone without legitimate cause, if he has not treated you wrongly.", topic: "Wisdom" },
  { reference: "Proverbs 31:30", text: "Charm is deceitful and beauty is fleeting. A woman who fears the LORD– she makes herself praiseworthy.", topic: "Marriage" },
  { reference: "Proverbs 31:31", text: "Give her credit for what she has accomplished, and let her works praise her in the city gates.", topic: "Money" },
  { reference: "Proverbs 4:5", text: "Acquire wisdom, acquire understanding; do not forget and do not turn aside from the words I speak.", topic: "Speech" },
  { reference: "Proverbs 4:6", text: "Do not forsake wisdom, and she will protect you; love her, and she will guard you.", topic: "Wisdom" },
  { reference: "Proverbs 1:1", text: "The Proverbs of Solomon, son of David, king of Israel:", topic: "Family" },
  { reference: "Proverbs 1:2", text: "To learn wisdom and moral instruction, to discern wise counsel.", topic: "Wisdom" },
  { reference: "Proverbs 1:3", text: "To receive moral instruction in skillful living, with righteousness, justice, and equity.", topic: "Integrity" },
  { reference: "Proverbs 1:4", text: "To impart shrewdness to the morally naive, a discerning plan to the young person.", topic: "Wisdom" },
  { reference: "Proverbs 1:5", text: "(Let the wise also hear and gain instruction, and let the discerning acquire guidance!)", topic: "Wisdom" },
  { reference: "Proverbs 1:6", text: "To discern the meaning of a proverb and a parable, the sayings of the wise and their riddles.", topic: "Wisdom" },
  { reference: "Proverbs 1:7", text: "Fearing the LORD is the beginning of discernment, but fools have despised wisdom and moral instruction.", topic: "Wisdom" },
  { reference: "Proverbs 10:11", text: "The speech of the righteous is a fountain of life, but the speech of the wicked conceals violence.", topic: "Speech" },
  { reference: "Proverbs 11:2", text: "After pride came, disgrace followed; but wisdom came with humility.", topic: "Pride" },
  { reference: "Proverbs 12:15", text: "The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise.", topic: "Wisdom" },
  { reference: "Proverbs 13:10", text: "With pride comes only contention, but wisdom is with the well-advised.", topic: "Pride" },
  { reference: "Proverbs 15:28", text: "The heart of the righteous considers how to answer, but the mouth of the wicked pours out evil things.", topic: "Speech" },
  { reference: "Proverbs 16:16", text: "How much better it is to acquire wisdom than gold; to acquire understanding is more desirable than silver.", topic: "Money" },
  { reference: "Proverbs 16:21", text: "The one who is wise in heart is called discerning, and kind speech increases persuasiveness.", topic: "Speech" },
  { reference: "Proverbs 17:16", text: "What’s the point of a fool having money in hand to buy wisdom, when his head is empty?", topic: "Money" },
  { reference: "Proverbs 17:28", text: "Even a fool who remains silent is considered wise, and the one who holds his tongue is deemed discerning.", topic: "Speech" },
  { reference: "Proverbs 18:14", text: "A person’s spirit sustains him through sickness – but who can bear a crushed spirit?", topic: "Heart" },
  { reference: "Proverbs 18:16", text: "A person’s gift makes room for him, and leads him before important people.", topic: "Wisdom" },
  { reference: "Proverbs 20:4", text: "The sluggard will not plow by reason of the cold; therefore shall he beg in harvest, and have nothing.", topic: "Work" },
  { reference: "Proverbs 21:22", text: "A wise man went up against the city of the mighty and brought down the stronghold in which they trust.", topic: "Wisdom" },
  { reference: "Proverbs 24:28", text: "Be not a witness against thy neighbour without cause; and deceive not with thy lips.", topic: "Speech" },
  { reference: "Proverbs 28:22", text: "The stingy person hastens after riches and does not know that poverty will overtake him.", topic: "Money" },
  { reference: "Proverbs 29:18", text: "When there is no prophetic vision the people cast off restraint, but the one who keeps the law, blessed is he!", topic: "Wisdom" },
  { reference: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life.", topic: "Heart" },
];

export const WISDOM_LIBRARY: WisdomQuote[] = [
  { source: "John Gottman", text: "Happy marriages are based on a deep friendship. By this I mean a mutual respect for and enjoyment of each other's company.", topic: "Friendship" },
  { source: "John Gottman", text: "70% of the quality of a marriage is determined by the quality of the friendship.", topic: "Friendship" },
  { source: "John Gottman", text: "Successful repair attempts are the secret weapon of emotionally intelligent couples.", topic: "Repair" },
  { source: "Willard Harley", text: "Love Busters are habits that drain the Love Bank. The most common are angry outbursts, disrespectful judgments, and annoying behavior.", topic: "Love Busters" },
  { source: "Willard Harley", text: "Her top emotional needs are often Affection, Conversation, Honesty and Openness, Financial Support, and Family Commitment.", topic: "Needs" },
  { source: "Shaunti Feldhahn", text: "Most women have a 'window' open in their brain for everything they are worried about. Help her close the windows by listening.", topic: "Listening" },
  { source: "Shaunti Feldhahn", text: "When she says 'We need to talk,' she usually means 'I need to feel close to you.'", topic: "Speech" },
  { source: "Ellen G. White", text: "Love cannot exist without expression. Let not the heart be withered for want of kindness.", topic: "Affection" },
  { source: "Ellen G. White", text: "The husband is the house-band of the home treasures, binding by his strong, earnest, devoted affection the members of the household.", topic: "Leadership" },
  { source: "Adventist Home", text: "Determine to be all that it is possible to be to each other. Continue the early attentions.", topic: "Romance" }
];

export const SAMPLE_DEVOTIONALS: Devotional[] = [
  {
    id: 1,
    day: 1,
    skill: "Awareness",
    role: "Listener",
    title: "Leadership Briefing",
    truth: "Today, your wife needs to feel emotionally safe more than she needs answers.",
    anchor: {
      source: "James 1:19",
      text: "Let every man be swift to hear, slow to speak."
    },
    insight: "When you listen without correcting or defending, she feels valued rather than evaluated. Even when you disagree internally, your calm presence tells her, 'I'm with you, not against you.' That sense of safety builds trust far faster than solutions ever could.",
    action: "Before noon, ask her one question about how she's feeling—and do not fix, explain, or compare.",
    exactWords: "I want to understand what today feels like for you.",
    path: "faith"
  },
  {
    id: 2,
    day: 2,
    skill: "Awareness",
    role: "Husband",
    title: "One Thing She Wishes You Knew",
    truth: "Most wives feel emotionally disconnected long before they say anything.",
    anchor: {
      source: "Marriage Research",
      text: "Emotional withdrawal often precedes conflict—not the other way around."
    },
    insight: "You may think, 'If she's quiet, things must be okay.' But silence may mean she doesn't yet feel safe enough to speak—or doesn't believe speaking will change anything.",
    action: "Ask her the 'Hidden Insight' question today.",
    exactWords: "Is there anything you've been holding back that you wish I understood better?",
    path: "wisdom"
  },
  {
    id: 3,
    day: 3,
    skill: "Response",
    role: "Protector",
    title: "Marriage Micro-Mission",
    truth: "Feeling understood calms the nervous system.",
    anchor: {
      source: "Proverbs 15:1",
      text: "A soft answer turns away wrath, but a harsh word stirs up anger."
    },
    insight: "When she feels emotionally safe, connection grows naturally. Your mission is to build that safety through validation.",
    action: "Validate her feelings today, even if you don't agree with the facts.",
    exactWords: "That makes sense. I can see why you'd feel that way.",
    path: "faith"
  },
  {
    id: 4,
    day: 4,
    skill: "Repair",
    role: "Repairer",
    title: "Love Buster → Love Builder",
    truth: "Defensiveness kills intimacy faster than criticism.",
    anchor: {
      source: "1 Corinthians 13:4",
      text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud."
    },
    insight: "Defensiveness usually shows up as explaining your intentions instead of acknowledging her feelings. The 'Love Builder' replacement is empathy before explanation.",
    action: "Catch yourself being defensive today. Stop, breathe, and validate instead.",
    exactWords: "I was about to defend myself, but I want to hear you first.",
    path: "wisdom"
  },
  {
    id: 5,
    day: 5,
    skill: "Awareness",
    role: "Friend",
    title: "Her Emotional Need Today",
    truth: "Conversation isn't about exchanging information—it's about emotional connection.",
    anchor: {
      source: "Gottman Institute",
      text: "Turning towards bids for connection is the basis of trust."
    },
    insight: "Listening without multitasking communicates interest more than words. Give her 10 uninterrupted minutes today. Phone down. Eyes up.",
    action: "Initiate 10 minutes of 'floor time' where she talks and you just listen.",
    exactWords: "I have 10 minutes and I'd love to hear about your day.",
    path: "faith"
  },
  {
    id: 6,
    day: 6,
    skill: "Awareness",
    role: "Spiritual Leader",
    title: "Pray Like a Husband",
    truth: "Prayer softens your heart before it changes her behavior.",
    anchor: {
      source: "Psalm 139:23",
      text: "Search me, O God, and know my heart."
    },
    insight: "Often we pray for our wives to change. Today, pray for wisdom to love her well. It changes the atmosphere of your heart.",
    action: "Pray this simple 3-sentence prayer.",
    exactWords: "God, thank You for my wife. Help me notice where my tone creates distance. Give me wisdom to love her well today.",
    path: "wisdom"
  },
  {
    id: 7,
    day: 7,
    skill: "Repair",
    role: "Repairer",
    title: "Repair Skill of the Day",
    truth: "Strong marriages aren't conflict-free—they're repair-rich.",
    anchor: {
      source: "Gottman Institute",
      text: "Successful repair attempts are the primary difference between masters and disasters of marriage."
    },
    insight: "Small misunderstandings turn into emotional distance if left alone. A simple repair phrase can stop the spiral.",
    action: "Use the repair phrase the moment you sense tension.",
    exactWords: "That came out wrong. Let me try again.",
    path: "faith"
  }
];